// DocEase - Main JavaScript File

// Common utility functions
const utils = {
    showNotification: function(message, type = 'info') {
        // Create notification element
        const notification = document.createElement('div');
        notification.className = `notification notification-${type}`;
        notification.textContent = message;
        notification.style.cssText = `
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 1rem 1.5rem;
            background: ${type === 'success' ? '#2ecc71' : type === 'error' ? '#e74c3c' : '#3498db'};
            color: white;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            z-index: 1000;
            animation: slideIn 0.3s ease;
            max-width: 300px;
        `;
        
        document.body.appendChild(notification);
        
        // Remove after 3 seconds
        setTimeout(() => {
            notification.style.animation = 'slideOut 0.3s ease';
            setTimeout(() => {
                document.body.removeChild(notification);
            }, 300);
        }, 3000);
    },
    
    downloadTextFile: function(text, filename) {
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    },
    
    copyToClipboard: function(text) {
        navigator.clipboard.writeText(text).then(() => {
            this.showNotification('Copied to clipboard!', 'success');
        }).catch(err => {
            console.error('Failed to copy: ', err);
            // Fallback method
            const textarea = document.createElement('textarea');
            textarea.value = text;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            this.showNotification('Copied to clipboard!', 'success');
        });
    }
};

// Add CSS for notifications
const notificationStyles = `
@keyframes slideIn {
    from { transform: translateX(100%); opacity: 0; }
    to { transform: translateX(0); opacity: 1; }
}

@keyframes slideOut {
    from { transform: translateX(0); opacity: 1; }
    to { transform: translateX(100%); opacity: 0; }
}
`;

const styleSheet = document.createElement('style');
styleSheet.textContent = notificationStyles;
document.head.appendChild(styleSheet);

// Text to PDF Converter Functionality
if (document.getElementById('convertBtn')) {
    const textInput = document.getElementById('textInput');
    const convertBtn = document.getElementById('convertBtn');
    const clearBtn = document.getElementById('clearBtn');
    const sampleBtn = document.getElementById('sampleBtn');
    
    convertBtn.addEventListener('click', function() {
        if (!textInput.value.trim()) {
            utils.showNotification('Please enter some text to convert', 'error');
            return;
        }
        
        const text = textInput.value;
        const printWindow = window.open('', '_blank');
        
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>Document from DocEase</title>
                <style>
                    body { 
                        font-family: Arial, sans-serif; 
                        line-height: 1.6; 
                        margin: 2cm; 
                        color: #333;
                    }
                    .header { 
                        text-align: center; 
                        margin-bottom: 2rem;
                        border-bottom: 2px solid #4361ee;
                        padding-bottom: 1rem;
                    }
                    .content { 
                        white-space: pre-wrap; 
                        font-size: 12pt;
                    }
                    .footer {
                        text-align: center;
                        margin-top: 3rem;
                        font-size: 10pt;
                        color: #666;
                        border-top: 1px solid #eee;
                        padding-top: 1rem;
                    }
                    @page { margin: 2cm; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Document</h1>
                    <p>Generated by DocEase - Free Document Converter</p>
                </div>
                <div class="content">${text.replace(/\n/g, '<br>')}</div>
                <div class="footer">
                    <p>Created with DocEase - Free online document tools</p>
                    <p>https://yourdomain.com</p>
                </div>
            </body>
            </html>
        `);
        
        printWindow.document.close();
        
        // Wait for content to load before printing
        setTimeout(() => {
            printWindow.print();
        }, 500);
    });
    
    clearBtn.addEventListener('click', function() {
        textInput.value = '';
        textInput.focus();
    });
    
    sampleBtn.addEventListener('click', function() {
        textInput.value = `DOCUMENT TITLE
Created with DocEase Text to PDF Converter

Introduction:
This is a sample document showing how text will appear when converted to PDF. You can paste any text content - articles, reports, letters, or any other documents.

Key Features:
• Converts text to PDF instantly
• Works entirely in your browser
• No registration required
• Your data never leaves your computer

Instructions:
1. Enter or paste your text
2. Click "Convert to PDF"
3. Use browser's print dialog to save as PDF

Benefits:
- Free to use
- Privacy focused
- Works on all devices
- No file size limits

Conclusion:
DocEase provides free document conversion tools for users worldwide. Whether you're in India, USA, or anywhere else, our tools work seamlessly to meet your document needs.

Generated on: ${new Date().toLocaleDateString()}
`;
    });
}

// Resume Formatter Functionality
if (document.getElementById('formatResumeBtn')) {
    const resumeInput = document.getElementById('resumeInput');
    const formatResumeBtn = document.getElementById('formatResumeBtn');
    const resumeClearBtn = document.getElementById('resumeClearBtn');
    const resumeSampleBtn = document.getElementById('resumeSampleBtn');
    const copyResumeBtn = document.getElementById('copyResumeBtn');
    const downloadResumeBtn = document.getElementById('downloadResumeBtn');
    const resumePreview = document.getElementById('resumePreview');
    
    function formatResumeText(text) {
        // Split into lines
        let lines = text.split('\n');
        let formattedLines = [];
        let inBulletList = false;
        
        for (let i = 0; i < lines.length; i++) {
            let line = lines[i].trim();
            
            // Skip empty lines at the beginning
            if (line === '' && formattedLines.length === 0) continue;
            
            // Detect sections
            if (line.match(/^(PROFESSIONAL SUMMARY|WORK EXPERIENCE|EDUCATION|SKILLS|CERTIFICATIONS|PROJECTS|REFERENCES)/i)) {
                if (formattedLines.length > 0 && formattedLines[formattedLines.length - 1] !== '') {
                    formattedLines.push('');
                }
                formattedLines.push(line.toUpperCase());
                formattedLines.push('');
                inBulletList = false;
            }
            // Detect bullet points
            else if (line.match(/^[•\-*]\s+|^\d+\.\s+/)) {
                if (!inBulletList && formattedLines.length > 0) {
                    formattedLines.push('');
                }
                formattedLines.push('  • ' + line.replace(/^[•\-*]\s+|^\d+\.\s+/, ''));
                inBulletList = true;
            }
            // Detect contact info
            else if (line.match(/@|\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/) && formattedLines.length < 3) {
                formattedLines.push(line);
            }
            // Regular text
            else if (line !== '') {
                if (inBulletList) {
                    formattedLines.push('');
                    inBulletList = false;
                }
                formattedLines.push(line);
            }
            // Empty lines
            else if (formattedLines.length > 0 && formattedLines[formattedLines.length - 1] !== '') {
                formattedLines.push('');
                inBulletList = false;
            }
        }
        
        // Create HTML preview
        let htmlPreview = '<div class="resume-content">';
        for (let line of formattedLines) {
            if (line === '') {
                htmlPreview += '<div class="resume-spacing"></div>';
            } else if (line.match(/^(PROFESSIONAL SUMMARY|WORK EXPERIENCE|EDUCATION|SKILLS|CERTIFICATIONS|PROJECTS|REFERENCES)/)) {
                htmlPreview += `<h4 class="resume-section">${line}</h4>`;
            } else if (line.startsWith('  • ')) {
                htmlPreview += `<div class="resume-bullet">${line}</div>`;
            } else if (formattedLines.indexOf(line) < 3) {
                htmlPreview += `<div class="resume-header">${line}</div>`;
            } else {
                htmlPreview += `<div class="resume-text">${line}</div>`;
            }
        }
        htmlPreview += '</div>';
        
        return {
            text: formattedLines.join('\n'),
            html: htmlPreview
        };
    }
    
    formatResumeBtn.addEventListener('click', function() {
        if (!resumeInput.value.trim()) {
            utils.showNotification('Please enter resume content', 'error');
            return;
        }
        
        const formatted = formatResumeText(resumeInput.value);
        resumePreview.innerHTML = formatted.html;
        
        // Enable copy and download buttons
        copyResumeBtn.disabled = false;
        downloadResumeBtn.disabled = false;
        
        // Store formatted text in button data
        copyResumeBtn.dataset.text = formatted.text;
        downloadResumeBtn.dataset.text = formatted.text;
        
        utils.showNotification('Resume formatted successfully!', 'success');
    });
    
    resumeClearBtn.addEventListener('click', function() {
        resumeInput.value = '';
        resumePreview.innerHTML = '<p class="preview-placeholder">Your formatted resume will appear here...</p>';
        copyResumeBtn.disabled = true;
        downloadResumeBtn.disabled = true;
        resumeInput.focus();
    });
    
    resumeSampleBtn.addEventListener('click', function() {
        resumeInput.value = `JANE SMITH
Senior Marketing Manager
New York, NY | (555) 123-4567 | jane.smith@email.com | linkedin.com/in/janesmith

PROFESSIONAL SUMMARY
Results-driven marketing professional with 8+ years of experience in digital marketing, brand strategy, and team leadership. Proven track record of increasing brand visibility and driving revenue growth.

WORK EXPERIENCE
Senior Marketing Manager - Tech Innovations Inc. (2019-Present)
- Led digital marketing campaigns resulting in 150% increase in online engagement
- Managed team of 5 marketing specialists
- Developed and executed social media strategy across 4 platforms
- Increased quarterly revenue by 35% through targeted campaigns

Marketing Specialist - Global Solutions Ltd. (2016-2019)
- Executed email marketing campaigns with 40% open rate
- Managed company blog producing 50+ articles monthly
- Assisted in rebranding initiative that increased market share by 15%

EDUCATION
MBA in Marketing - Stanford University (2014-2016)
Bachelor of Business Administration - University of Michigan (2010-2014)

SKILLS
- Digital Marketing Strategy
- Social Media Management
- Google Analytics & SEO
- Team Leadership
- Budget Management
- Content Creation

CERTIFICATIONS
- Google Ads Certified
- HubSpot Inbound Marketing Certified
- Facebook Blueprint Certified`;
        
        utils.showNotification('Sample resume loaded', 'info');
    });
    
    copyResumeBtn.addEventListener('click', function() {
        if (this.dataset.text) {
            utils.copyToClipboard(this.dataset.text);
        }
    });
    
    downloadResumeBtn.addEventListener('click', function() {
        if (this.dataset.text) {
            utils.downloadTextFile(this.dataset.text, 'formatted-resume.txt');
        }
    });
}

// Word Text Cleaner Functionality
if (document.getElementById('cleanTextBtn')) {
    const dirtyText = document.getElementById('dirtyText');
    const cleanText = document.getElementById('cleanText');
    const cleanerClearBtn = document.getElementById('cleanerClearBtn');
    const cleanerSampleBtn = document.getElementById('cleanerSampleBtn');
    const cleanTextBtn = document.getElementById('cleanTextBtn');
    const copyCleanBtn = document.getElementById('copyCleanBtn');
    const downloadCleanBtn = document.getElementById('downloadCleanBtn');
    
    const optionExtraSpaces = document.getElementById('optionExtraSpaces');
    const optionLineBreaks = document.getElementById('optionLineBreaks');
    const optionTabs = document.getElementById('optionTabs');
    const optionTrim = document.getElementById('optionTrim');
    
    function cleanTextContent(text) {
        let cleaned = text;
        
        // Replace tabs with spaces
        if (optionTabs.checked) {
            cleaned = cleaned.replace(/\t/g, '    ');
        }
        
        // Remove extra spaces
        if (optionExtraSpaces.checked) {
            // Replace multiple spaces with single space
            cleaned = cleaned.replace(/[ \t]+/g, ' ');
            // Fix space after newlines
            cleaned = cleaned.replace(/\n /g, '\n');
            cleaned = cleaned.replace(/ \n/g, '\n');
        }
        
        // Fix unnecessary line breaks
        if (optionLineBreaks.checked) {
            // Remove single line breaks within paragraphs
            cleaned = cleaned.replace(/([^\n])\n([^\n])/g, '$1 $2');
            // Fix multiple consecutive newlines (keep at most 2)
            cleaned = cleaned.replace(/\n{3,}/g, '\n\n');
        }
        
        // Trim beginning and end
        if (optionTrim.checked) {
            cleaned = cleaned.trim();
        }
        
        return cleaned;
    }
    
    cleanTextBtn.addEventListener('click', function() {
        if (!dirtyText.value.trim()) {
            utils.showNotification('Please enter text to clean', 'error');
            return;
        }
        
        const cleaned = cleanTextContent(dirtyText.value);
        cleanText.value = cleaned;
        
        // Enable copy and download buttons
        copyCleanBtn.disabled = false;
        downloadCleanBtn.disabled = false;
        
        utils.showNotification('Text cleaned successfully!', 'success');
    });
    
    cleanerClearBtn.addEventListener('click', function() {
        dirtyText.value = '';
        cleanText.value = '';
        copyCleanBtn.disabled = true;
        downloadCleanBtn.disabled = true;
        dirtyText.focus();
    });
    
    cleanerSampleBtn.addEventListener('click', function() {
        dirtyText.value = `This   is   a   sample   document   with   multiple   spacing   issues.

It   also   contains

unnecessary

line

breaks

that   need   to   be   fixed.

Sometimes,   when   copying   from   Word   documents,   you   get   these   formatting   problems.

Bullet   points   also   have   issues:
•   First   point   with   extra   spaces
•   Second   point   with   formatting   problems

Numbered   lists   too:
1.   Item   one
2.   Item   two
3.   Item   three

The   quick   brown   fox   jumps   over   the   lazy   dog.      This   sentence   has   many   spaces.

Another   paragraph   with   line   break   issues   that   make   the   text   hard   to   read   and   process   in   other   applications.`;
        
        utils.showNotification('Sample text loaded', 'info');
    });
    
    copyCleanBtn.addEventListener('click', function() {
        if (cleanText.value) {
            utils.copyToClipboard(cleanText.value);
        }
    });
    
    downloadCleanBtn.addEventListener('click', function() {
        if (cleanText.value) {
            utils.downloadTextFile(cleanText.value, 'cleaned-text.txt');
        }
    });
}

// PDF Text Extractor Functionality
if (document.getElementById('pdfUpload')) {
    const pdfUpload = document.getElementById('pdfUpload');
    const dropArea = document.getElementById('dropArea');
    const selectedFile = document.getElementById('selectedFile');
    const fileName = document.getElementById('fileName');
    const extractBtn = document.getElementById('extractBtn');
    const clearFileBtn = document.getElementById('clearFileBtn');
    const extractedText = document.getElementById('extractedText');
    const copyExtractedBtn = document.getElementById('copyExtractedBtn');
    const downloadExtractedBtn = document.getElementById('downloadExtractedBtn');
    const cleanExtractedBtn = document.getElementById('cleanExtractedBtn');
    
    let currentFile = null;
    
    // Drag and drop functionality
    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
        dropArea.addEventListener(eventName, preventDefaults, false);
    });
    
    function preventDefaults(e) {
        e.preventDefault();
        e.stopPropagation();
    }
    
    ['dragenter', 'dragover'].forEach(eventName => {
        dropArea.addEventListener(eventName, highlight, false);
    });
    
    ['dragleave', 'drop'].forEach(eventName => {
        dropArea.addEventListener(eventName, unhighlight, false);
    });
    
    function highlight() {
        dropArea.style.borderColor = '#4361ee';
        dropArea.style.backgroundColor = '#f0f5ff';
    }
    
    function unhighlight() {
        dropArea.style.borderColor = '#ccc';
        dropArea.style.backgroundColor = '';
    }
    
    dropArea.addEventListener('drop', handleDrop, false);
    
    function handleDrop(e) {
        const dt = e.dataTransfer;
        const files = dt.files;
        
        if (files.length > 0) {
            handleFile(files[0]);
        }
    }
    
    pdfUpload.addEventListener('change', function(e) {
        if (e.target.files.length > 0) {
            handleFile(e.target.files[0]);
        }
    });
    
    function handleFile(file) {
        // Check if it's a PDF
        if (!file.type.includes('pdf') && !file.name.toLowerCase().endsWith('.pdf')) {
            utils.showNotification('Please select a PDF file', 'error');
            return;
        }
        
        // Check file size (10MB limit)
        if (file.size > 10 * 1024 * 1024) {
            utils.showNotification('File size must be less than 10MB', 'error');
            return;
        }
        
        currentFile = file;
        fileName.textContent = file.name;
        selectedFile.style.display = 'block';
        
        // Reset extracted text
        extractedText.value = '';
        copyExtractedBtn.disabled = true;
        downloadExtractedBtn.disabled = true;
        cleanExtractedBtn.disabled = true;
        
        utils.showNotification('PDF file selected', 'success');
    }
    
    extractBtn.addEventListener('click', function() {
        if (!currentFile) {
            utils.showNotification('Please select a PDF file first', 'error');
            return;
        }
        
        utils.showNotification('Extracting text... This may take a moment', 'info');
        
        const reader = new FileReader();
        
        reader.onload = function(e) {
            try {
                // Note: This is a basic implementation
                // In a real scenario, you would use a PDF parsing library
                // Since we can't use external libraries, we'll provide instructions
                // and a fallback method for text extraction
                
                const text = `PDF Text Extraction - Browser Limitation

Due to browser security restrictions and the requirement to not use external libraries, 
direct PDF text extraction in JavaScript is limited.

However, you can extract text from your PDF using these methods:

METHOD 1: Browser's Built-in Feature
1. Open your PDF in Chrome or Edge
2. Select all text (Ctrl+A or Cmd+A)
3. Copy the text (Ctrl+C or Cmd+C)
4. Paste it into the box below

METHOD 2: Online Tools
For reliable PDF text extraction, consider these free online tools:
• Smallpdf.com
• ILovePDF.com
• Adobe's online PDF tools

METHOD 3: Native Applications
• Adobe Acrobat Reader (free)
• Preview on Mac
• Microsoft Edge browser

Once you've extracted the text using one of these methods, 
you can paste it here and use our cleaning tools to format it.

File Information:
• Name: ${currentFile.name}
• Size: ${(currentFile.size / 1024).toFixed(2)} KB
• Type: ${currentFile.type}

For future versions, we plan to implement proper PDF text extraction 
when browser APIs improve or when we can use appropriate libraries.`;

                extractedText.value = text;
                
                // Enable buttons
                copyExtractedBtn.disabled = false;
                downloadExtractedBtn.disabled = false;
                cleanExtractedBtn.disabled = false;
                
                utils.showNotification('PDF processed successfully', 'success');
            } catch (error) {
                console.error('PDF extraction error:', error);
                utils.showNotification('Error processing PDF. Please try another file or method.', 'error');
            }
        };
        
        reader.onerror = function() {
            utils.showNotification('Error reading file', 'error');
        };
        
        reader.readAsArrayBuffer(currentFile);
    });
    
    clearFileBtn.addEventListener('click', function() {
        pdfUpload.value = '';
        currentFile = null;
        selectedFile.style.display = 'none';
        extractedText.value = '';
        copyExtractedBtn.disabled = true;
        downloadExtractedBtn.disabled = true;
        cleanExtractedBtn.disabled = true;
    });
    
    copyExtractedBtn.addEventListener('click', function() {
        if (extractedText.value) {
            utils.copyToClipboard(extractedText.value);
        }
    });
    
    downloadExtractedBtn.addEventListener('click', function() {
        if (extractedText.value) {
            utils.downloadTextFile(extractedText.value, 'extracted-text.txt');
        }
    });
    
    cleanExtractedBtn.addEventListener('click', function() {
        if (extractedText.value) {
            window.location.href = 'word-text-cleaner.html';
        }
    });
}

// Homepage textarea auto-resize
document.querySelectorAll('textarea').forEach(textarea => {
    textarea.addEventListener('input', function() {
        this.style.height = 'auto';
        this.style.height = (this.scrollHeight) + 'px';
    });
});

// Initialize textareas on page load
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('textarea').forEach(textarea => {
        textarea.style.height = 'auto';
        textarea.style.height = (textarea.scrollHeight) + 'px';
    });
});